name: modsec
services:
  web:
    container_name: web
    image: nginxdemos/nginx-hello
    depends_on:
      - modsec
    networks:
      - isolated

  modsec:
    container_name: modsec
    image: owasp/modsecurity-crs:${MODSECURITY_TAG}
    volumes:
      - ./src/html:/usr/share/nginx/html
      - ./src/etc/nginx/templates/conf.d/eebt.conf.template:/etc/nginx/templates/conf.d/eebt.conf.template
      - ./src/etc/nginx/templates/conf.d/logging.conf.template:/etc/nginx/templates/conf.d/logging.conf.template
      - ./src/etc/nginx/templates/includes/location_common.conf.template:/etc/nginx/templates/includes/location_common.conf.template
      - ./src/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/opt/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - ./src/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/opt/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    env_file: modsec.env
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - isolated
      - public

networks:
  isolated:
    driver: bridge
    internal: true
  public:
    driver: bridge
