name: modsec
services:
  web:
    container_name: web
    image: nginxdemos/nginx-hello
    depends_on:
      - modsec
    networks:
      - isolated
      - public
    ports:
      - "8181:8080"

  modsec:
    container_name: modsec
    build:
      context: ./src
      args:
        MODSECURITY_TAG: 4.6.0-nginx-alpine-202409130109
    env_file: modsec.env
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - isolated
      - public

  errorhandler:
    container_name: errorhandler
    image: php:8-fpm
    restart: always
    volumes:
      - ./src/html:/usr/share/nginx/html
      - ./conf/app-php.ini:/usr/local/etc/php/conf.d/app-php.ini
    ports:
      - 9000:9000
    depends_on:
      - modsec
    networks:
      - isolated

networks:
  isolated:
    driver: bridge
    internal: true
  public:
    driver: bridge
