name: modsec
services:
  web:
    container_name: web
    image: nginxdemos/nginx-hello
    depends_on:
      - modsec
    networks:
      - isolated
      - public
    ports:
      - "8181:8080"

  modsec:
    container_name: modsec
#    image: owasp/modsecurity-crs:${MODSECURITY_TAG}
    build:
      context: ./src
      args:
        MODSECURITY_TAG: ${MODSECURITY_TAG}
    env_file: modsec.env
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - isolated
      - public


networks:
  isolated:
    driver: bridge
    internal: true
  public:
    driver: bridge
